language: python
os:
  - linux
sudo: required
services:
  - docker
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"

env:
  - PARALLELIZE=true

before_install:
  - python --version
  - pip install -U pip
  - pip install --default-timeout 60 setuptools coverage coveralls pytest nose-timer && export HAS_COVERALLS=1
  - docker pull tinkerpop/gremlin-server
  - docker run --name gremlin-server -d -p 8182:8182 tinkerpop/gremlin-server
  - docker ps -a

install:
  - pip install -r requirements.txt
  - pip install ".[test]" . # install package + test dependencies

script:
  - pytest --cov=rdf2g test

after_success:
  - if [[ $HAS_COVERALLS ]] ; then coveralls ; fi
